Add ConfigurationToConfigurations planner adapter.
personalrobotics/aikido pull request #587
Opened 2020-10-04 22:49 UTC by brianhou

This PR introduces the DART `ConfigurationToConfigurations` problem and planner. It also introduces an adapter from non-DART `ConfigurationToConfigurationPlanner` to DART `ConfigurationToConfigurationsPlanner`.

I think the ideal scenario would be to have two adapters instead:
- non-DART `ConfigurationToConfigurationPlanner` to non-DART `ConfigurationToConfigurationsPlanner`
- non-DART `ConfigurationToConfigurationsPlanner` to DART `ConfigurationToConfigurationsPlanner`

This isn't supported by the current `PlannerAdapter`, since the adapted planner must be a DART planner. However, I've also added the non-DART `ConfigurationToConfigurations` planner, which might eventually be useful for this purpose.

***

**Before creating a pull request**

- [ ] Document new methods and classes
- [ ] Format code with `make format`

**Before merging a pull request**

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change

2020-10-06 19:06 UTC, sniyaz requested changes
Thanks so much for doing this! Just a few small issues: LMK when you're done, and I'll reformat and make sure Travis is happy before merging.

2020-10-06 19:06 UTC, sniyaz commented on src/planner/dart/ConfigurationToConfiguration_to_ConfigurationToConfigurations.cpp
> +  for (const auto& goal : problem.getGoalStates())
Nit: Is there a reason to use a ref here? I think each `goal` is just a pointer/adress.

2020-10-06 22:28 UTC, brianhou commented on include/aikido/planner/dart/ConfigurationToConfiguration_to_ConfigurationToConfigurations.hpp
> +      Planner::Result* result) override;
That only seems to be the default in the VectorFieldPlanner, so I'm inclined to leave it as is for now.

2020-10-07 08:36 UTC, sniyaz commented on include/aikido/planner/dart/ConfigurationToConfiguration_to_ConfigurationToConfigurations.hpp
> +      Planner::Result* result) override;
Sounds good!

2020-10-07 08:40 UTC, sniyaz approved these changes
Thanks for the changes @brianhou! I fixed some really tiny things and ran make format, and this looks great.

Will merge once Travis looks good.

2020-10-07 10:48 UTC, merged