Adding conversion from SphereShape to ROS msg
personalrobotics/aikido pull request #601
Opened 2021-07-12 21:49 UTC by Haoyangerrr-MoMo

[Describe this pull request. Link to relevant GitHub issues, if any.]
Adding convertShape for SphereShape under rviz/shape_conversion.cpp.

[Explain how this pull request was tested.]

***

**Before creating a pull request**

- [ ] Document new methods and classes
- [ ] Format code with `make format`

**Before merging a pull request**

- [ ] Set version target by selecting a milestone on the right side
- [ ] Summarize this change in `CHANGELOG.md`
- [ ] Add unit test(s) for this change

2021-07-12 22:03 UTC, hejia-zhang approved these changes

2021-07-20 00:27 UTC, egordon requested changes
Looks good in general! some things to do first:

(1) Run make format
(2) Add a description of this to the CHANGELOG under RVIZ.
(3) Assign it to Aikido v0.5 milestone

2021-08-13 17:28 UTC, egordon commented
@Haoyangerrr-MoMo 
@hejia-zhang 
Reminder that you'll need to address these (small) changes before we can merge this PR!

2021-08-24 03:11 UTC, egordon approved these changes

2021-08-24 03:12 UTC, merged